//
//  SearchViewController.swift
//  MusicApp
//
//  Created admin on 24/03/2020.
//  Copyright © 2020 SangNX. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class SearchViewController: BaseViewController {
    
    @IBOutlet weak var tbView: UITableView!
    
    private lazy var search = { () -> UISearchController in
        let search = UISearchController(searchResultsController: nil)
        search.searchBar.placeholder = "Search music"
        return search
    }()
    
	var presenter: SearchPresenterProtocol?
    
    var albums = ["Classical Music", "K-POP", "Chilren's Music", "Nursery Rhymes"]
    
	override func viewDidLoad() {
        super.viewDidLoad()
        setUpViews()
        setUpTbView()
    }
    
    private func setUpViews() {
        self.navigationItem.searchController = search
    }
    
    private func setUpTbView() {
        tbView.registerXibFile(TrendingView.self)
        tbView.registerXibFile(AlbumView.self)
        tbView.separatorStyle = .none
        tbView.dataSource = self
        tbView.delegate = self
        tbView.contentInset = UIEdgeInsets(top: 0, left: 0, bottom: 50, right: 0)
    }
}

extension SearchViewController: UITableViewDataSource, UITableViewDelegate, TrendingViewDelegate, AlbumViewDelegate
{
    func numberOfSections(in tableView: UITableView) -> Int {
        return 2
    }
    
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return section == 0 ? 1 : albums.count
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        if indexPath.section == 0 {
            let cell = tableView.dequeueTableCell(TrendingView.self)
            cell.lblTitle.text = "Trending in Viet Nam"
            cell.delegate = self
            return cell
        } else {
            let cell = tableView.dequeueTableCell(AlbumView.self)
            cell.delegate = self
            cell.keyword = albums[indexPath.row]
            return cell
        }
    }
    
    func tableView(_ tableView: UITableView, heightForRowAt indexPath: IndexPath) -> CGFloat {
        return indexPath.section == 0 ? 415 : 290
    }
    
    func onPressViewSeeAll(keyword: String) {
        let playlistVC = PlaylistRouter.createModule(type: .normal, keyword: keyword)
        self.push(controller: playlistVC)
    }
    
    func onPressViewSeeAll() {
        let playlistVC = PlaylistRouter.createModule(type: .trending, keyword: "Trending in Viet Nam")
        self.push(controller: playlistVC)
    }
}

extension SearchViewController: SearchViewProtocol
{
    
}
