//
//  SearchPresenter.swift
//  MusicApp
//
//  Created admin on 24/03/2020.
//  Copyright © 2020 SangNX. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class SearchPresenter: SearchPresenterProtocol, SearchInteractorOutputProtocol {
    
    weak private var view: SearchViewProtocol?
    var interactor: SearchInteractorInputProtocol?
    private let router: SearchWireframeProtocol

    init(interface: SearchViewProtocol, interactor: SearchInteractorInputProtocol?, router: SearchWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

    func startSearchWith(keyword: String, maxResult: Int, pageToken: String) {
        interactor?.requestSearchWith(keyword: keyword, maxResult: maxResult, pageToken: pageToken)
    }
    
    func onResponseSearchSuccess(response: SearchResponse) {
        view?.responseSearchSuccess(response: response)
    }
    
    func onResponseSearchFail(error: String) {
        view?.responseSearchFail(error: error)
    }
    
}
