//
//  SearchViewController.swift
//  MusicApp
//
//  Created admin on 22/03/2020.
//  Copyright © 2020 SangNX. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class SearchViewController: UIViewController, SearchViewProtocol {

    @IBOutlet weak var tbView: UITableView!
    
    var presenter: SearchPresenterProtocol?

    override func viewDidLoad() {
        super.viewDidLoad()
        
        let search = UISearchController(searchResultsController: nil)
        search.delegate = self
        self.navigationItem.searchController = search
        
        self.view.backgroundColor = .clear
        self.tbView.backgroundColor = .clear
    }

}

extension SearchViewController: UISearchControllerDelegate
{
    
    
}
