//
//  SearchProtocols.swift
//  MusicApp
//
//  Created admin on 22/03/2020.
//  Copyright © 2020 SangNX. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol SearchWireframeProtocol: class {

}
//MARK: Presenter -
protocol SearchPresenterProtocol: class {

}

//MARK: Interactor -
protocol SearchInteractorProtocol: class {

  var presenter: SearchPresenterProtocol?  { get set }
}

//MARK: View -
protocol SearchViewProtocol: class {

  var presenter: SearchPresenterProtocol?  { get set }
}
