//
//  SearchInteractor.swift
//  MusicApp
//
//  Created admin on 22/03/2020.
//  Copyright © 2020 SangNX. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class SearchInteractor: SearchInteractorProtocol {

    weak var presenter: SearchPresenterProtocol?
}
