//
//  SearchProtocols.swift
//  MusicApp
//
//  Created admin on 24/03/2020.
//  Copyright © 2020 SangNX. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol SearchWireframeProtocol: class {

}
//MARK: Presenter -
protocol SearchPresenterProtocol: class {

    var interactor: SearchInteractorInputProtocol? { get set }
    
    func startSearchWith(keyword: String, maxResult: Int, pageToken: String)
    
}

//MARK: Interactor -
protocol SearchInteractorOutputProtocol: class {

    /* Interactor -> Presenter */
    
    func onResponseSearchSuccess(response: SearchResponse)
    func onResponseSearchFail(error: String)
    
}

protocol SearchInteractorInputProtocol: class {

    var presenter: SearchInteractorOutputProtocol?  { get set }

    /* Presenter -> Interactor */
    func requestSearchWith(keyword: String, maxResult: Int, pageToken: String)
}

//MARK: View -
protocol SearchViewProtocol: class {

    var presenter: SearchPresenterProtocol?  { get set }

    /* Presenter -> ViewController */
   func responseSearchSuccess(response: SearchResponse)
   func responseSearchFail(error: String)
}
