//
//  MoreInteractor.swift
//  MusicApp
//
//  Created admin on 22/03/2020.
//  Copyright © 2020 SangNX. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class MoreInteractor: MoreInteractorProtocol {

    weak var presenter: MorePresenterProtocol?
}
