//
//  MorePresenter.swift
//  MusicApp
//
//  Created admin on 22/03/2020.
//  Copyright © 2020 SangNX. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class MorePresenter: MorePresenterProtocol {

    weak private var view: MoreViewProtocol?
    var interactor: MoreInteractorProtocol?
    private let router: MoreWireframeProtocol

    init(interface: MoreViewProtocol, interactor: MoreInteractorProtocol?, router: MoreWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}
