//
//  PlaylistProtocols.swift
//  MusicApp
//
//  Created admin on 24/03/2020.
//  Copyright © 2020 SangNX. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol PlaylistWireframeProtocol: class {

}
//MARK: Presenter -
protocol PlaylistPresenterProtocol: class {

    var interactor: PlaylistInteractorInputProtocol? { get set }
    
    func startGetListTrendingMusic(pageToken: String, maxResult: Int)
}

//MARK: Interactor -
protocol PlaylistInteractorOutputProtocol: class {

    /* Interactor -> Presenter */
    func onResponseGetListTrendingMusicSuccess(response: BaseResponse)
    func onResponseGetListTrendingMusicFail(error: String)
}

protocol PlaylistInteractorInputProtocol: class {

    var presenter: PlaylistInteractorOutputProtocol?  { get set }

    /* Presenter -> Interactor */
    func requestGetListTrendingMusic(pageToken: String, maxResult: Int)
}

//MARK: View -
protocol PlaylistViewProtocol: class {

    var presenter: PlaylistPresenterProtocol?  { get set }

    /* Presenter -> ViewController */
    func responseGetListTrendingMusicSuccess(response: BaseResponse)
    func responseGetListTrendingMusicFail(error: String)
}
