//
//  PlaylistViewController.swift
//  MusicApp
//
//  Created admin on 24/03/2020.
//  Copyright © 2020 SangNX. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

enum PlaylistViewControllerType {
    case trending
    case normal
}

class PlaylistViewController: BaseTableViewController {
    
	var presenter: PlaylistPresenterProtocol?
    var type: PlaylistViewControllerType = .normal
    
	override func viewDidLoad() {
        super.viewDidLoad()
        setUpViews()
        fetchData()
    }
    
    private func setUpViews() {
        self.title = "Trending in Viet Nam"
        myTableView.registerXibFile(TrendingTbvCell.self)
        myTableView.separatorStyle = .none
        myTableView.dataSource = self
        myTableView.delegate = self
    }
    
    override func setHeightForRow() -> CGFloat {
        return 65
    }
    
    override func fetchData() {
        super.fetchData()
        if type == .trending && listItem.count < 50 {
            self.presenter?.startGetListTrendingMusic(pageToken: "", maxResult: 50)
        }
    }
    
    override func cellForRowAt(item: Any, for indexPath: IndexPath, tableView: UITableView) -> UITableViewCell {
        let cell = tableView.dequeueTableCell(TrendingTbvCell.self)
        if let snippet = (item as! Item).snippet, let thumbnails = snippet.thumbnails {
            cell.img.loadImageFromInternet(link: thumbnails.defaults!.url!)
            cell.lblTitle.text = snippet.title
            cell.lblChanel.text = snippet.channelTitle
            cell.lblRow.text = "#\(indexPath.row + 1)"
        }
        return cell
    }

}

extension PlaylistViewController: PlaylistViewProtocol
{
    func responseGetListTrendingMusicSuccess(response: BaseResponse) {
        self.didFetchData(data: response.items!)
    }
    
    func responseGetListTrendingMusicFail(error: String) {
        
    }
    
    
}
