//
//  PlaylistProtocols.swift
//  MusicApp
//
//  Created admin on 24/03/2020.
//  Copyright © 2020 SangNX. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol PlaylistWireframeProtocol: class {

}
//MARK: Presenter -
protocol PlaylistPresenterProtocol: class {

    var interactor: PlaylistInteractorInputProtocol? { get set }
    
    func startGetListMusic(pageToken: String, maxResult: Int, type: PlaylistViewControllerType, keyword: String)
}

//MARK: Interactor -
protocol PlaylistInteractorOutputProtocol: class {

    /* Interactor -> Presenter */
    func onResponseGetListMusicSuccess(response: SearchResponse)
    func onResponseGetListMusicFail(error: String)
    
    func onResponseGetListTrendingMusicSuccess(response: VideosResponse)
}

protocol PlaylistInteractorInputProtocol: class {

    var presenter: PlaylistInteractorOutputProtocol?  { get set }

    /* Presenter -> Interactor */
    func requestGetListMusic(pageToken: String, maxResult: Int, type: PlaylistViewControllerType, keyword: String)
}

//MARK: View -
protocol PlaylistViewProtocol: class {

    var presenter: PlaylistPresenterProtocol?  { get set }

    /* Presenter -> ViewController */
    func responseGetListMusicSuccess(response: SearchResponse)
    func responseGetListMusicFail(error: String)
    
    func responseGetListTrendingMusicSuccess(response: VideosResponse)
}
