//
//  PlaylistInteractor.swift
//  MusicApp
//
//  Created admin on 24/03/2020.
//  Copyright © 2020 SangNX. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class PlaylistInteractor: PlaylistInteractorInputProtocol {

    weak var presenter: PlaylistInteractorOutputProtocol?
    
    func requestGetListTrendingMusic(pageToken: String, maxResult: Int) {
        Provider.shared.callApiTrendingVideo(pageToken: pageToken, maxResult: maxResult, success: { (BaseResponse) in
            self.presenter?.onResponseGetListTrendingMusicSuccess(response: BaseResponse)
        }) { (error) in
            self.presenter?.onResponseGetListTrendingMusicFail(error: error)
        }
    }
}
