//
//  PlaylistInteractor.swift
//  MusicApp
//
//  Created admin on 24/03/2020.
//  Copyright © 2020 SangNX. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class PlaylistInteractor: PlaylistInteractorInputProtocol {

    weak var presenter: PlaylistInteractorOutputProtocol?
    
    func requestGetListMusic(pageToken: String, maxResult: Int, type: PlaylistType, keyword: String) {
        if type == .trending {
            Provider.shared.callApiTrendingVideo(pageToken: pageToken, maxResult: maxResult, success: { (BaseResponse) in
                self.presenter?.onResponseGetListTrendingMusicSuccess(response: BaseResponse)
            }) { (error) in
                self.presenter?.onResponseGetListMusicFail(error: error)
            }
        } else {
            Provider.shared.callApiGetListVideo(pageToken: pageToken, maxResult: maxResult, keyword: keyword, success: { (BaseResponse) in
                self.presenter?.onResponseGetListMusicSuccess(response: BaseResponse)
            }) { (error) in
                self.presenter?.onResponseGetListMusicFail(error: error)
            }
        }
    }
}
