//
//  PlaylistRouter.swift
//  MusicApp
//
//  Created admin on 24/03/2020.
//  Copyright © 2020 SangNX. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class PlaylistRouter: PlaylistWireframeProtocol {

    weak var viewController: UIViewController?

    static func createModule(type: PlaylistType, keyword: String) -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = PlaylistViewController(nibName: nil, bundle: nil)
        let interactor = PlaylistInteractor()
        let router = PlaylistRouter()
        let presenter = PlaylistPresenter(interface: view, interactor: interactor, router: router)

        view.type = type
        view.keyword = keyword
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view

        return view
    }
}
