//
//  PlaylistPresenter.swift
//  MusicApp
//
//  Created admin on 24/03/2020.
//  Copyright © 2020 SangNX. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class PlaylistPresenter: PlaylistPresenterProtocol, PlaylistInteractorOutputProtocol {

    weak private var view: PlaylistViewProtocol?
    var interactor: PlaylistInteractorInputProtocol?
    private let router: PlaylistWireframeProtocol

    init(interface: PlaylistViewProtocol, interactor: PlaylistInteractorInputProtocol?, router: PlaylistWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }
    
    func startGetListTrendingMusic(pageToken: String, maxResult: Int) {
        interactor?.requestGetListTrendingMusic(pageToken: pageToken, maxResult: maxResult)
    }
    
    func onResponseGetListTrendingMusicSuccess(response: BaseResponse) {
        view?.responseGetListTrendingMusicSuccess(response: response)
    }
    
    func onResponseGetListTrendingMusicFail(error: String) {
        view?.responseGetListTrendingMusicFail(error: error)
    }

}
