//
//  PlaylistPresenter.swift
//  MusicApp
//
//  Created admin on 24/03/2020.
//  Copyright © 2020 SangNX. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class PlaylistPresenter: PlaylistPresenterProtocol, PlaylistInteractorOutputProtocol {

    weak private var view: PlaylistViewProtocol?
    var interactor: PlaylistInteractorInputProtocol?
    private let router: PlaylistWireframeProtocol

    init(interface: PlaylistViewProtocol, interactor: PlaylistInteractorInputProtocol?, router: PlaylistWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }
    
    func startGetListMusic(pageToken: String, maxResult: Int, type: PlaylistType, keyword: String) {
        interactor?.requestGetListMusic(pageToken: pageToken, maxResult: maxResult, type: type, keyword: keyword)
    }
    
    func onResponseGetListMusicSuccess(response: SearchResponse) {
        view?.responseGetListMusicSuccess(response: response)
    }
    
    func onResponseGetListMusicFail(error: String) {
        view?.responseGetListMusicFail(error: error)
    }
    
    func onResponseGetListTrendingMusicSuccess(response: VideosResponse) {
        view?.responseGetListTrendingMusicSuccess(response: response)
    }

}
