//
//  PersonPlayListRouter.swift
//  MusicApp
//
//  Created Sang on 4/4/20.
//  Copyright © 2020 SangNX. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class PersonPlayListRouter: PersonPlayListWireframeProtocol {
    
    weak var viewController: UIViewController?
    
    static func createModule() -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = PersonPlayListViewController(nibName: nil, bundle: nil)
        let interactor = PersonPlayListInteractor()
        let router = PersonPlayListRouter()
        let presenter = PersonPlayListPresenter(interface: view, interactor: interactor, router: router)
        
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
        
        return view
    }
}
