//
//  PersonPlayListPresenter.swift
//  MusicApp
//
//  Created Sang on 4/4/20.
//  Copyright © 2020 SangNX. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class PersonPlayListPresenter: PersonPlayListPresenterProtocol {

    weak private var view: PersonPlayListViewProtocol?
    var interactor: PersonPlayListInteractorProtocol?
    private let router: PersonPlayListWireframeProtocol

    init(interface: PersonPlayListViewProtocol, interactor: PersonPlayListInteractorProtocol?, router: PersonPlayListWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}
