//
//  PersonPlayListInteractor.swift
//  MusicApp
//
//  Created Sang on 4/4/20.
//  Copyright © 2020 SangNX. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class PersonPlayListInteractor: PersonPlayListInteractorProtocol {

    weak var presenter: PersonPlayListPresenterProtocol?
}
