//
//  PlayMusicPresenter.swift
//  MusicApp
//
//  Created Sang on 3/28/20.
//  Copyright © 2020 SangNX. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class PlayMusicPresenter: PlayMusicPresenterProtocol {

    weak private var view: PlayMusicViewProtocol?
    var interactor: PlayMusicInteractorProtocol?
    private let router: PlayMusicWireframeProtocol

    init(interface: PlayMusicViewProtocol, interactor: PlayMusicInteractorProtocol?, router: PlayMusicWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}
