//
//  PlayMusicViewController.swift
//  MusicApp
//
//  Created Sang on 3/28/20.
//  Copyright © 2020 SangNX. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit
import youtube_ios_player_helper

class PlayMusicViewController: BaseViewController, PlayMusicViewProtocol {
    
    @IBOutlet weak var videoView: YTPlayerView!
    var presenter: PlayMusicPresenterProtocol?
    var item: Item! = nil
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        let playvarsDic = ["playsinline": 1, "origin" : "http://www.youtube.com"] as [String : Any]
        if let utubeModel = item, let videoId = utubeModel.id {
            videoView.load(withVideoId: videoId, playerVars: playvarsDic)
        }
    }
}
