//
//  PlayMusicProtocols.swift
//  MusicApp
//
//  Created Sang on 3/28/20.
//  Copyright © 2020 SangNX. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol PlayMusicWireframeProtocol: class {

}
//MARK: Presenter -
protocol PlayMusicPresenterProtocol: class {

}

//MARK: Interactor -
protocol PlayMusicInteractorProtocol: class {

  var presenter: PlayMusicPresenterProtocol?  { get set }
}

//MARK: View -
protocol PlayMusicViewProtocol: class {

  var presenter: PlayMusicPresenterProtocol?  { get set }
}
