//
//  PlayMusicRouter.swift
//  MusicApp
//
//  Created Sang on 3/28/20.
//  Copyright © 2020 SangNX. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class PlayMusicRouter: PlayMusicWireframeProtocol {
    
    weak var viewController: UIViewController?
    
    static func createModule() -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = PlayMusicViewController(nibName: nil, bundle: nil)
        let interactor = PlayMusicInteractor()
        let router = PlayMusicRouter()
        let presenter = PlayMusicPresenter(interface: view, interactor: interactor, router: router)
        
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
        
        return view
    }
}
