//
//  PlayMusicInteractor.swift
//  MusicApp
//
//  Created Sang on 3/28/20.
//  Copyright © 2020 SangNX. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class PlayMusicInteractor: PlayMusicInteractorProtocol {

    weak var presenter: PlayMusicPresenterProtocol?
}
